# Generated by Django 3.0.6 on 2020-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('section_type', models.TextField()),
            ],
        ),
    ]
